# Generated by Django 4.0.4 on 2022-05-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'managed': False},
        ),
    ]
