school_data = [
    {
        "abbreviation": "AN",
        "name": "Annenberg School For Communication",
        "visibility": True,
        "opendata_abbr": "AN",
        "canvas_subaccount": 99243,
    },
    {
        "abbreviation": "SAS",
        "name": "Arts & Sciences",
        "visibility": True,
        "opendata_abbr": "AS",
        "canvas_subaccount": 99237,
    },
    {
        "abbreviation": "DM",
        "name": "Dental Medicine",
        "visibility": True,
        "opendata_abbr": "DM",
        "canvas_subaccount": 99241,
    },
    {
        "abbreviation": "GSE",
        "name": "Graduate School Of Education",
        "visibility": False,
        "opendata_abbr": "ED",
        "canvas_subaccount": 82192,
    },
    {
        "abbreviation": "SEAS",
        "name": "Engineering",
        "visibility": True,
        "opendata_abbr": "EG",
        "canvas_subaccount": 99238,
    },
    {
        "abbreviation": "FA",
        "name": "Design",
        "visibility": True,
        "opendata_abbr": "FA",
        "canvas_subaccount": 99244,
    },
    {"abbreviation": "LW", "name": "Law", "visibility": True, "opendata_abbr": "LW"},
    {
        "abbreviation": "PSOM",
        "name": "Perelman School Of Medicine",
        "visibility": True,
        "opendata_abbr": "MD",
        "canvas_subaccount": 99242,
    },
    {
        "abbreviation": "NURS",
        "name": "Nursing",
        "visibility": True,
        "opendata_abbr": "NU",
        "canvas_subaccount": 99239,
    },
    {
        "abbreviation": "PC",
        "name": "Provost Center",
        "visibility": True,
        "opendata_abbr": "PV",
    },
    {
        "abbreviation": "SS",
        "name": "Summer Sessions",
        "visibility": True,
        "opendata_abbr": "SS",
    },
    {
        "abbreviation": "SP2",
        "name": "Social Policy & Practice",
        "visibility": True,
        "opendata_abbr": "SW",
        "canvas_subaccount": 99240,
    },
    {
        "abbreviation": "VET",
        "name": "Veterinary Medicine",
        "visibility": True,
        "opendata_abbr": "VM",
        "canvas_subaccount": 132153,
    },
    {
        "abbreviation": "WH",
        "name": "Wharton",
        "visibility": True,
        "opendata_abbr": "WH",
        "canvas_subaccount": 81471,
    },
]
