repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        args: [--experimental-string-processing]
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [--max-line-length=88]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies:
          [types-Markdown==3.3.6, types-requests==2.25.11]
  - repo: local
    hooks:
      - id: django-test
        name: django-test
        entry: python manage.py test tests
        pass_filenames: false
        language: system
