# Generated by Django 2.1.2 on 2021-09-23 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20210623_1458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tools',
        ),
    ]
