# Generated by Django 2.1.2 on 2021-10-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_delete_tools"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="lps_online",
            field=models.BooleanField(default=False),
        ),
    ]
