# Generated by Django 2.1.2 on 2021-10-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_request_lps_online"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="exclude_announcements",
            field=models.BooleanField(default=False),
        ),
    ]
