# Generated by Django 2.1.2 on 2021-10-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_autoadd_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["abbr"],
                "verbose_name": "Activity Type",
                "verbose_name_plural": "Activity Types",
            },
        ),
        migrations.AlterModelOptions(
            name="canvassite",
            options={"ordering": ["canvas_id"]},
        ),
        migrations.AlterModelOptions(
            name="school",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ["name"]},
        ),
        migrations.RenameField(
            model_name="school",
            old_name="opendata_abbr",
            new_name="open_data_abbreviation",
        ),
        migrations.AlterField(
            model_name="request",
            name="lps_online",
            field=models.BooleanField(default=False, verbose_name="LPS Online"),
        ),
    ]
