# Generated by Django 2.1.2 on 2021-10-29 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0008_auto_20211028_1302"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"ordering": ["abbr"], "verbose_name_plural": "Activites"},
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["-year", "course_code"]},
        ),
        migrations.AlterModelOptions(
            name="requestsummary",
            options={"verbose_name_plural": "Requests summaries"},
        ),
    ]
